id: PEB8D7EE1
initial_creation_type: input
source_metadata:
  title: Kṣitigarbha Series
  language: bo
  description: 'Texts related to Kṣitigarbha (sa’i snying po), one of the eight great
    bodhisattvas:'
  volume:
    c377ee72b1544f809111115a2f5abf73:
      title: 'Beautiful Adornment of the Earth: In Praise of Kṣitigarbha'
      parent: Praise
    ba11fb3657f44c009c108183182f0f8b:
      title: Kṣitigarbha Visualization and Mantra Recitation
      parent: Sādhanas
created_at: '2022-03-01T04:05:33.138655'
last_modified_at: '2022-03-01T04:05:33.138658'
